/**
 * This class is generated by jOOQ
 */
package com.github.georgealvessilveira.jooq_extension_lib.jooqs;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -1749871890;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.CATEGORIA_ID_SEQ,
			Sequences.ENDERECO_ID_SEQ,
			Sequences.INGREDIENTE_ID_SEQ,
			Sequences.ITEM_PEDIDO_ID_SEQ,
			Sequences.ITEMESTOQUE_ID_SEQ,
			Sequences.PEDIDO_ID_SEQ,
			Sequences.PESSOA_ID_SEQ,
			Sequences.PRODUTO_ID_SEQ,
			Sequences.TBL_CAIXA_ID_SEQ,
			Sequences.TBL_CATEGORIA_ID_SEQ,
			Sequences.TBL_CONFIGURACOES_ID_SEQ,
			Sequences.TBL_ENDERECO_ID_SEQ,
			Sequences.TBL_ESTOQUE_ID_SEQ,
			Sequences.TBL_INGREDIENTE_ID_SEQ,
			Sequences.TBL_ITEM_ESTOCAVEL_ID_SEQ,
			Sequences.TBL_ITEM_PEDIDO_ID_SEQ,
			Sequences.TBL_MOVIMENTACAO_ID_SEQ,
			Sequences.TBL_PEDIDO_ID_SEQ,
			Sequences.TBL_PRODUTO_ID_SEQ,
			Sequences.TBL_SAT_ID_SEQ,
			Sequences.TBL_TELEFONE_ID_SEQ,
			Sequences.TELEFONE_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			TblUsuario.TBL_USUARIO);
	}
}
