/**
 * This class is generated by jOOQ
 */
package com.github.georgealvessilveira.jooq_extension_lib.jooqs;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.categoria_id_seq</code>
	 */
	public static final Sequence<Long> CATEGORIA_ID_SEQ = new SequenceImpl<Long>("categoria_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.endereco_id_seq</code>
	 */
	public static final Sequence<Long> ENDERECO_ID_SEQ = new SequenceImpl<Long>("endereco_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.ingrediente_id_seq</code>
	 */
	public static final Sequence<Long> INGREDIENTE_ID_SEQ = new SequenceImpl<Long>("ingrediente_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.item_pedido_id_seq</code>
	 */
	public static final Sequence<Long> ITEM_PEDIDO_ID_SEQ = new SequenceImpl<Long>("item_pedido_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.itemestoque_id_seq</code>
	 */
	public static final Sequence<Long> ITEMESTOQUE_ID_SEQ = new SequenceImpl<Long>("itemestoque_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.pedido_id_seq</code>
	 */
	public static final Sequence<Long> PEDIDO_ID_SEQ = new SequenceImpl<Long>("pedido_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.pessoa_id_seq</code>
	 */
	public static final Sequence<Long> PESSOA_ID_SEQ = new SequenceImpl<Long>("pessoa_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.produto_id_seq</code>
	 */
	public static final Sequence<Long> PRODUTO_ID_SEQ = new SequenceImpl<Long>("produto_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_caixa_id_seq</code>
	 */
	public static final Sequence<Long> TBL_CAIXA_ID_SEQ = new SequenceImpl<Long>("tbl_caixa_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_categoria_id_seq</code>
	 */
	public static final Sequence<Long> TBL_CATEGORIA_ID_SEQ = new SequenceImpl<Long>("tbl_categoria_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_configuracoes_id_seq</code>
	 */
	public static final Sequence<Long> TBL_CONFIGURACOES_ID_SEQ = new SequenceImpl<Long>("tbl_configuracoes_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_endereco_id_seq</code>
	 */
	public static final Sequence<Long> TBL_ENDERECO_ID_SEQ = new SequenceImpl<Long>("tbl_endereco_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_estoque_id_seq</code>
	 */
	public static final Sequence<Long> TBL_ESTOQUE_ID_SEQ = new SequenceImpl<Long>("tbl_estoque_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_ingrediente_id_seq</code>
	 */
	public static final Sequence<Long> TBL_INGREDIENTE_ID_SEQ = new SequenceImpl<Long>("tbl_ingrediente_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_item_estocavel_id_seq</code>
	 */
	public static final Sequence<Long> TBL_ITEM_ESTOCAVEL_ID_SEQ = new SequenceImpl<Long>("tbl_item_estocavel_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_item_pedido_id_seq</code>
	 */
	public static final Sequence<Long> TBL_ITEM_PEDIDO_ID_SEQ = new SequenceImpl<Long>("tbl_item_pedido_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_movimentacao_id_seq</code>
	 */
	public static final Sequence<Long> TBL_MOVIMENTACAO_ID_SEQ = new SequenceImpl<Long>("tbl_movimentacao_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_pedido_id_seq</code>
	 */
	public static final Sequence<Long> TBL_PEDIDO_ID_SEQ = new SequenceImpl<Long>("tbl_pedido_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_produto_id_seq</code>
	 */
	public static final Sequence<Long> TBL_PRODUTO_ID_SEQ = new SequenceImpl<Long>("tbl_produto_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_sat_id_seq</code>
	 */
	public static final Sequence<Long> TBL_SAT_ID_SEQ = new SequenceImpl<Long>("tbl_sat_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tbl_telefone_id_seq</code>
	 */
	public static final Sequence<Long> TBL_TELEFONE_ID_SEQ = new SequenceImpl<Long>("tbl_telefone_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.telefone_id_seq</code>
	 */
	public static final Sequence<Long> TELEFONE_ID_SEQ = new SequenceImpl<Long>("telefone_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
