/**
 * This class is generated by jOOQ
 */
package com.github.georgealvessilveira.jooq_extension_lib.jooqs;


import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.tbl_usuario
	 */
	public static final TblUsuario TBL_USUARIO = TblUsuario.TBL_USUARIO;
}
